(function() {
    'use strict';


    const Mapping = require('./Mapping');



    module.exports = class AnresisSexMapping extends Mapping {


        constructor() {
            super();


            this.type = 'bacteria';

            this.map.set('Escherichia coli', 'escherichia coli');
            this.map.set('Enterococcus faecalis', 'enterococcus faecalis');
            this.map.set('Klebsiella pneumoniae subsp pneumoniae', 'klebsiella sp.');
            this.map.set('Klebsiella pneumoniae', 'klebsiella sp.');
            this.map.set('Enterococcus faecium', 'enterococcus faecium');
            this.map.set('Enterobacter cloacae', 'enterobacter sp.');
            this.map.set('Staphylococcus saprophyticus', 'staphylococcus saprophyticus');
            this.map.set('Staphylococcus epidermidis', 'staphylococcus epidermidis');
            this.map.set('Citrobacter freundii', 'citrobacter sp.');
            this.map.set('Staphylococcus aureus', 'staphylococcus aureus');
            this.map.set('Enterobacter aerogenes', 'enterobacter sp.');
            this.map.set('Proteus mirabilis', 'proteus mirabilis');
            this.map.set('Staphylococcus, coagulase-negative', 'staphylococcus epidermidis');
            this.map.set('Pseudomonas aeruginosa', 'pseudomonas aeruginosa');
            this.map.set('Klebsiella oxytoca', 'klebsiella sp.');
            this.map.set('Serratia marcescens', 'serratia sp.');
            this.map.set('Staphylococcus, coagulase-negative, not saprophyticus', 'staphylococcus epidermidis');
            this.map.set('Streptococcus pneumoniae', 'streptococcus pneumoniae');
            this.map.set('Citrobacter koseri', 'citrobacter sp.');
            this.map.set('Proteus vulgaris', 'proteus vulgaris');
            this.map.set('Morganella morganii', 'morganella sp.');
            this.map.set('Acinetobacter baumannii Komplex', 'acinetobacter sp.');
            this.map.set('Stenotrophomonas maltophilia', 'stenotrophomonas maltophilia');
            this.map.set('Klebsiella pneumoniae subsp ozaenae', 'klebsiella sp.');
            this.map.set('Enterobacter species', 'enterobacter sp.');
            this.map.set('Haemophilus influenzae', 'haemophilus influenzae');
            this.map.set('Citrobacter species', 'citrobacter sp.');
            this.map.set('Klebsiella species', 'klebsiella sp.');
            this.map.set('Citrobacter braakii', 'citrobacter sp.');
            this.map.set('Campylobacter jejuni', 'haemophilus ducreyi');
            this.map.set('Serratia rubidaea', 'burkholderia sp.');
            this.map.set('Acinetobacter junii', 'acinetobacter sp.');
            this.map.set('Acinetobacter parvus', 'acinetobacter sp.');
            this.map.set('Citrobacter freundii complex', 'citrobacter sp.');
            this.map.set('Enterobacter asburiae', 'enterobacter sp.');
            this.map.set('Mycobacterium tuberculosis', 'mycobacterium tuberculosis');
            this.map.set('Acinetobacter species', 'acinetobacter sp.');
            this.map.set('Citrobacter farmeri', 'citrobacter sp.');
            this.map.set('Enterobacter ludwigii', 'enterobacter sp.');
            this.map.set('Acinetobacter johnsonii', 'acinetobacter sp.');
            this.map.set('Serratia liquefaciens', 'serratia sp.');
            this.map.set('Acinetobacter baumannii', 'acinetobacter sp.');
            this.map.set('Salmonella species', 'salmonella sp.');
            this.map.set('Acinetobacter lwoffii', 'acinetobacter sp.');
            this.map.set('Enterobacter hormaechei', 'enterobacter sp.');
            this.map.set('Mycobacterium tuberculosis Komplex', 'mycobacterium tuberculosis');
            this.map.set('Enterobacter intermedius', 'enterobacter sp.');
            this.map.set('Serratia fonticola', 'serratia sp.');
            this.map.set('Salmonella ser. Enteritidis', 'salmonella sp.');
            this.map.set('Acinetobacter ursingii', 'acinetobacter sp.');
            this.map.set('Citrobacter youngae', 'citrobacter sp.');
            this.map.set('Serratia plymuthica', 'serratia sp.');
            this.map.set('Citrobacter amalonaticus', 'citrobacter sp.');
            this.map.set('Shigella flexneri', 'shigella sp.');
            this.map.set('Serratia odorifera', 'serratia sp.');
            this.map.set('Escherichia coli, enterohemorrhagic', 'citrobacter sp.');
            this.map.set('Salmonella ser. Typhimurium', 'salmonella sp.');
            this.map.set('Neisseria gonorrhoeae', 'neisseria gonorrhoeae');
            this.map.set('Serratia species', 'serratia sp.');
            this.map.set('Acinetobacter radioresistens', 'acinetobacter sp.');
            this.map.set('Enterobacter amnigenus', 'enterobacter sp.');
            this.map.set('Campylobacter coli', 'campylobacter sp.');
            this.map.set('Acinetobacter pittii', 'acinetobacter sp.');
            this.map.set('Salmonella subsp. enterica', 'salmonella sp.');
            this.map.set('Enterobacter gergoviae', 'enterobacter sp.');
            this.map.set('Shigella dysenteriae', 'shigella sp.');
            this.map.set('Acinetobacter haemolyticus', 'acinetobacter sp.');
            this.map.set('Salmonella group B', 'salmonella sp.');
            this.map.set('Stenotrophomonas maltophilia Komplex', 'stenotrophomonas maltophilia');
            this.map.set('Citrobacter werkmanii', 'citrobacter sp.');
            this.map.set('Acinetobacter calcoaceticus', 'acinetobacter sp.');
            this.map.set('Enterobacter kobei', 'enterobacter sp.');
            this.map.set('Serratia grimesii', 'serratia sp.');
            this.map.set('Acinetobacter guillouiae', 'acinetobacter sp.');
            this.map.set('Neisseria meningitidis', 'neisseria meningitidis');
            this.map.set('Enterobacter sakazakii', 'enterobacter sp.');
            this.map.set('Shigella sonnei', 'shigella sp.');
            this.map.set('Enterobacter taylorae', 'enterobacter sp.');
            this.map.set('Salmonella group C', 'salmonella sp.');
            this.map.set('Acinetobacter nosocomialis', 'acinetobacter sp.');
            this.map.set('Serratia ureilytica', 'serratia sp.');
            this.map.set('Campylobacter concisus', 'campylobacter sp.');
            this.map.set('Salmonella ser. Typhi', 'salmonella sp.');
            this.map.set('Salmonella ser. Bredeney', 'salmonella sp.');
            this.map.set('Salmonella ser. Napoli', 'salmonella sp.');
            this.map.set('Campylobacter fetus', 'campylobacter sp.');
            this.map.set('Campylobacter species', 'campylobacter sp.');
            this.map.set('Haemophilus influenzae-b', 'haemophilus influenzae');
            this.map.set('Salmonella ser. Bovismorbificans', 'salmonella sp.');
            this.map.set('Salmonella ser. Infantis', 'salmonella sp.');
            this.map.set('Salmonella ser. Paratyphi a', 'salmonella sp.');
            this.map.set('Shigella species', 'shigella sp.');
            this.map.set('Salmonella ser. Brandenburg', 'salmonella sp.');
            this.map.set('Salmonella ser. Elisabethville', 'salmonella sp.');
            this.map.set('Salmonella group D', 'salmonella sp.');
            this.map.set('Salmonella ser. Schwarzengrund', 'salmonella sp.');
            this.map.set('Salmonella group E', 'salmonella sp.');
            this.map.set('Citrobacter sedlakii', 'citrobacter sp.');
            this.map.set('Salmonella ser. München', 'salmonella sp.');
            this.map.set('Salmonella ser. Rissen', 'salmonella sp.');
            this.map.set('Salmonella ser. Paratyphi b', 'salmonella sp.');
            this.map.set('Salmonella ser. Panama', 'salmonella sp.');
            this.map.set('Salmonella ser. Stanley', 'salmonella sp.');
            this.map.set('Serratia ficaria', 'serratia sp.');
            this.map.set('Salmonella ser. Hadar', 'salmonella sp.');
            this.map.set('Salmonella ser. Stanleyville', 'salmonella sp.');
            this.map.set('Shigella boydii', 'serratia sp.');
            this.map.set('Salmonella ser. Eastbourne', 'salmonella sp.');
            this.map.set('Salmonella ser. Thompson', 'salmonella sp.');
            this.map.set('Salmonella ser. Braenderup', 'salmonella sp.');
            this.map.set('Campylobacter lari', 'campylobacter sp.');
            this.map.set('Salmonella ser. Mbandaka', 'salmonella sp.');
            this.map.set('Salmonella ser. Derby', 'salmonella sp.');
            this.map.set('Salmonella ser. Berta', 'salmonella sp.');
            this.map.set('Salmonella ser. Newport', 'salmonella sp.');
            this.map.set('Salmonella ser. Virchow', 'salmonella sp.');
            this.map.set('Salmonella ser. London', 'salmonella sp.');
            this.map.set('Salmonella ser. Kottbus', 'salmonella sp.');
            this.map.set('Campylobacter hyointestinalis subsp. hyointestinalis', 'campylobacter sp.');
            this.map.set('Salmonella ser. Goldcoast', 'salmonella sp.');
            this.map.set('Salmonella ser. Cholerasuis', 'salmonella sp.');
            this.map.set('Salmonella ser. Veneziana', 'salmonella sp.');
            this.map.set('Salmonella ser. Weltevreden', 'salmonella sp.');
            this.map.set('Salmonella subsp. arizonae', 'salmonella sp.');
            this.map.set('Salmonella ser. Oslo', 'salmonella sp.');
            this.map.set('Campylobacter upsaliensis', 'campylobacter sp.');
            this.map.set('Salmonella Ferruch', 'salmonella sp.');
            this.map.set('Salmonella ser. Dublin', 'salmonella sp.');
            this.map.set('Salmonella ser. Give', 'salmonella sp.');
            this.map.set('Salmonella ser. Heidelberg', 'salmonella sp.');
            this.map.set('Salmonella ser. Fischerhuette', 'salmonella sp.');
            this.map.set('Salmonella ser. Montevideo', 'salmonella sp.');
            this.map.set('Salmonella ser. Eboko', 'salmonella sp.');
            this.map.set('Salmonella ser. Kentucky', 'salmonella sp.');
            this.map.set('Salmonella ser. Livingstone', 'salmonella sp.');
            this.map.set('Salmonella ser. Aberdeen', 'salmonella sp.');
            this.map.set('Serratia proteamaculans', 'serratia sp.');
            this.map.set('Salmonella ser.  Brazzaville', 'salmonella sp.');
            this.map.set('Salmonella ser. Coeln', 'salmonella sp.');
            this.map.set('Salmonella ser. Ibadan', 'salmonella sp.');
            this.map.set('Salmonella ser. Oranienburg', 'salmonella sp.');
            this.map.set('Salmonella ser. Butantan', 'salmonella sp.');
            this.map.set('Salmonella ser. Chester', 'salmonella sp.');
            this.map.set('Acinetobacter baylyi', 'acinetobacter sp.');
        }
    };
})();
